### ISSUE TITLE
[édition multi-support] Margin en css

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#1070]
Dans le css de dodoc, il y a cette ligne css : 

```
._docViewer ._docViewer--content ._md[data-v-dc6782cd] > * {
  margin: 1em 0;
}
```

qui rentre en conflit avec du css custom pour l'édition multi-support.
c'est à dire que lorsque l'on souhaite régler le margin sur un élément, ça ne s'applique par à cause de cette déclarations css qui est plus précise. 
on est obligé de mettre un !important pour que ça fonctionne

**Comment by louis-ev** [comment]
Je corrige. 
Je bascule une bonne partie du css "vue" vers le css default pour pouvoir modifier tout, du coup.

**Comment by louis-ev** [comment]
Proposition, à tester sur test12 : 

```css
/* applies to web pages */
.web {
  margin: 0 auto;

  display: flex;
  flex-flow: row nowrap;
  align-items: flex-start;

  gap: calc(var(--spacing) * 2);
  padding: calc(var(--spacing) * 4) calc(var(--spacing) * 2);


  nav {
    flex: 0 0 15ch;
    ol {
      margin-left: calc(var(--spacing));
      li {
        margin: 0;
      }
    }
    button {
      color: var(--main-color);
      background: transparent;
      border: none;
      margin: 0;
      padding: 0.25em .5em;
      border-radius: 0.5em;
      cursor: pointer;
    }
    button.active {
      background: var(--main-color);
      color: white;
    }
  }
  section {
    h1 {
    }
    .content {
    }
  }
}
```
